sudo: required
services:
  - docker

before install:
  - docker build -t devkaush/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true devkaush/react-test npm test

after-success:
  - docker build -t devkaush/multi-client ./client
  - docker build -t devkaush/multi-nginx ./nginx
  - docker build -t devkaush/multi-server ./ server
  - docker build -t devkaush/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push devkaush/multi-client
  - docker push devkaush/multi-nginx
  - docker push devkaush/multi-server
  - docker push devkaush/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'ap-southeast-2'
  app: 'new-multi-docker'
  env: 'New-multi-docker-env'
  bucket_name: 'elasticbeanstalk-ap-southeast-2-623549006166'
  bucket_path: 'docker-new-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY